baseURL = 'https://learning.lllllan.cn'
locale = 'en-us'
title = 'Learning Log'
theme = 'papermod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  disableSpecial1stPost = true
  ShowToc = true
  TocOpen = true   # 默认展开，可选
